### ISSUE TITLE
Basis Login on UI not working, it works fine from swagger API

### ISSUE THREAD

**Issue by wap-datawizard** [startreedata/thirdeye#1103]
Login give error from the UI as not been configured
![Server.yaml Auth Config](https://github.com/startreedata/thirdeye/assets/102181238/092aa2ce-4872-44ba-98c6-7005d951980d)
![UI Error](https://github.com/startreedata/thirdeye/assets/102181238/47ed2233-01f9-44dc-abda-2536d33dc6c5)

**Comment by cyrilou242** [comment]
Discussions happened offline. 
This should be fixed, closing.
