### ISSUE TITLE
/api/app-analytics should add alert vs anomaly count stats

### ISSUE THREAD

**Issue by suvodeep-pyne** [startreedata/thirdeye#596]
The `/api/app-analytics` is intended to respond with useful stats around app usage.

This is currently a stub API at the moment. Goal is to enhance it with alert stats. The first stat the could be interesting is having a count of anomalies per alert.

Here's a possible starting point.

```json
{
  "version": "1.59.0-cc6fd8bc34461f3a2efd9e5ab41c3f1e698b7655",
  "alertStats": [
    {
      "id": 1234,
      "name": "my-alert-on-orders",
      "stats": {
        "anomalyCount": 24
      }
    },
    {
      "id": 2345,
      "name": "my-alert-on-orders-2",
      "stats": {
        "anomalyCount": 17
      }
    }
  ]
}
```

**Comment by cyrilou242** [comment]
not active anymore - closing
