### ISSUE TITLE
Is there any plan to support ClickHouse?

### ISSUE THREAD

**Issue by ljie-PI** [startreedata/thirdeye#656]

**Comment by mmantri2022** [comment]
Hello @ljie-PI 

We do not support connector for ClickHouse. 

For quick start you can try StarTree Community Edition for free. it includes StarTree Pinot and StarTree ThirdEye Community edition. Here is the link to the [StarTree Community Edition](https://get.startree.ai/startree-community-edition) and you can join our slack channel [here](https://communityinviter.com/apps/startreedata/startree-community).

Thanks!

**Comment by ljie-PI** [comment]
Thanks @mmantri2022 . Then is there interface to implement it by ourselves? Since we already have a big ClickHouse based OLAP platform and we need to reuse it.

**Comment by mmantri2022** [comment]
Thanks for your interest. This is not possible right now.

**Comment by ljie-PI** [comment]
Thank @mmantri2022.
