### ISSUE TITLE
What's the purpose of the change in LICENSE? 

### ISSUE THREAD

**Issue by ljie-PI** [startreedata/thirdeye#662]
What's the purpose of the change in LICENSE? Can we change the code and use in our internal projects?

**Comment by shounakmk219** [comment]
Hi @ljie-PI, 
[ThirdEye License FAQs](https://www.startree.ai/legal) will be a good place to find the answers to your question.

**Comment by ljie-PI** [comment]
Thanks @shounakmk219 . I will look for answer there.
